# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\"\x1f\n\x0fMyRequestSchema\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x10MyResponseSchema\x12\x0f\n\x07message\x18\x01 \x01(\t2L\n\tMyService\x12?\n\x18my_remote_call_procedure\x12\x10.MyRequestSchema\x1a\x11.MyResponseSchemab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MYREQUESTSCHEMA']._serialized_start=14
  _globals['_MYREQUESTSCHEMA']._serialized_end=45
  _globals['_MYRESPONSESCHEMA']._serialized_start=47
  _globals['_MYRESPONSESCHEMA']._serialized_end=82
  _globals['_MYSERVICE']._serialized_start=84
  _globals['_MYSERVICE']._serialized_end=160
# @@protoc_insertion_point(module_scope)
